### ISSUE TITLE
Site owners don't have edit access to their site

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#110]
## Steps to reproduce the issue

  1. Make someone the site owner of a site.
  1. Make sure they are not listed in Manage > Members except as being the site owner.

## Results

Site is not listed at https://cleanslate.wvu.edu/dashboard for the site owner. They don't have edit access to the site they own.

## Expected results

Anyone who's a site owner should have Admin access to their site.

This could be a result of [this recent commit](https://github.com/wvuweb/cleanslate/commit/39da9e1a0450ed9e8819a00cf37e0d39b8ec3dad). It's now highlighted since we listed the site owner in Manage > Members.

### Environment

Any/all.

### Temporary workaround

Add the site owner as a site member with admin privileges.

**Comment by nreckart** [comment]
Fixed in 8f27ebf2ca3689.

This had nothing to do with the recent commit mentioned. It was an over site that has been there all along and was never noticed, possibly because someone started advising that owners should also be added as admins, which helped conceal the issue. It was limited to the site list on the dashboard and the quick search bar. Owned sites weren't being included. Site ownership is handled separate from membership, which is a carry over from slate. In the future it may be wise pull ownership into membership.

Since
