### ISSUE TITLE
Pagination buttons do not work when the blog-index layout is being used for the homepage. 

### ISSUE THREAD

**Issue by TatsuJohnson** [wvuweb/cleanslate-cms#111]
When using the blog-index layout for the homepage, the pagination button does not point to the correct url and results in the page not being found. 

An example can be seen on http://wvlawreview.sandbox.wvu.edu

## Steps to reproduce the issue

1. Go into a site in Cleanslate that uses the blog-index layout for their homepage.

2. Try to use the pagination buttons to read older or newer articles. 

 

## Results

This webpage is not available

## Expected results

It is supposed to display the older articles in the blog area. 

### Environment

![screen shot 2015-01-28 at 2 09 41 pm](https://cloud.githubusercontent.com/assets/7927516/5944751/5b63d686-a6f7-11e4-835c-5bd8874988d7.png)

**Comment by adamjohnson** [comment]
Tatsu, could you edit your issue to follow the format outlined in the [contribution guidelines](https://github.com/wvuweb/cleanslate-cms/blob/master/CONTRIBUTING.md)? That will help us debug your bug report.

**Comment by adamjohnson** [comment]
:+1: Thanks Tatsu.

**Comment by TatsuJohnson** [comment]
It does work sometimes for some reason. 

![screen shot 2015-01-29 at 4 37 48 pm](https://cloud.githubusercontent.com/assets/7927516/5966800/68f777ec-a7d5-11e4-8480-2560f006028b.png)

**Comment by nreckart** [comment]
It's busted because you're using the blog index page as the home page. So when it's trying to build the pagination links for the the first page (wvlawreview.sandbox.wvu.edu/) there is no page slug for it to build off of, so it's generating wvlawreview.sandbox.wvu.edu/page/2, which isn't a valid URL. In your screenshot above, you're on http://wvlawreview.sandbox.wvu.edu/west-virginia-law-review-online/page/2, which has a page slug (west-virginia-law-review-online) to work with, so it generates a valid URL. 

If you go to http://wvlawreview.sandbox.wvu.edu/west-virginia-law-review-online, things work fine. So it's just a matter of making the pagination stuff smart enough to handle being the 'home' page.

**Comment by nreckart** [comment]
@TatsuJohnson should be fixed.
