### ISSUE TITLE
Feature Request -- Allow content editor to left, center, and right align text

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#112]
There is no way for a content editor to align text without using code in the HTML editor.  It would be nice to have this basic text editing capability added to the editing screen.

**Comment by adamjohnson** [comment]
Josh, do you have a use case for where this may be legit and applicable?

Center, right align and full justified buttons have been intentionally removed due to our experiences with "creative" content editors meddling with typography in Slate. You can see this kind of abuse [here](http://careerservices.wvu.edu/) under "Visit our office" ([epic rivers!](http://cl.ly/ZVJv)). Center align and other crazy things ran rampant on the old HR site, decreasing readability and degrading the brand.

Our belief is that if you want to align text, that decision should be up to the designer of the site, not the content editor. The rate of which it's abused is far greater than the rate of which it's used tastefully by content editors.

**Comment by joshrcook** [comment]
I don't doubt that content editors could potentially abuse any capability that they have.  I've seen several pages on our own site that looked horrible because they didn't use consistent headings throughout the page, had paragraphs in bold throughout, etc.  

However, my thought is that rather than restricting that through technological measures, shouldn't those be perfect opportunities for training about the brand and what best practices are?  That way content editors who actually know what they are doing can get their work done without necessarily having to know what div to apply `text-align: center` to in order to get a button centered.

For example, this is a page that Lisa was recently working on where I think text-align: center was used tastefully, but I had to show her how to code it up:

http://it.wvu.edu/services/training

**Comment by dmolsen** [comment]
@joshrcook -

We will not be enabling this feature. While it may appear to be "a basic text editing capability" it is one that can be quickly abused. I don't disagree with your example but in order to ensure a modicum of type consistency across University websites we're going to default to left justified text.

What this might show is that we need to better educate prof techs on HTML/CSS if they need to make minor tweaks to specific content. If Lisa has a similar question in the future she is free to ask us directly too.
