### ISSUE TITLE
Request: Keyboard shortcuts for tables in editor

### ISSUE THREAD

**Issue by chrisyuska** [wvuweb/cleanslate-cms#154]
Keyboard shortcuts to navigate and modify tables in the editor would be helpful for users to maintain tables on their site without having to know html or have to repeatedly use the mouse.  Something similar to popular spreadsheet software would be nice.
- `tab` - move to next cell (create new row when in last cell)
- `shift + tab` - move to previous cell
- `enter` - move to next row (create new row when in last row)
- `shift + enter` - move to previous row
- `ctrl + enter` - newline in focused cell
- `backspace` - delete row when in empty cell of empty row

**Comment by dmolsen** [comment]
This would be a bit time consuming to write. Not overly difficult just quite a bit of vanilla JS so it won't be delivered until the second half of the year. I can take on the task of writing it since I have experience from other projects. I need to be able to do the following:
- [ ] add keyboard shortcut tracking JS to both the content region and page (e.g. inside and outside the iframe)
- [ ] add postMessage support to pass the keyboard shortcuts into the iframe
- [ ] create JS that should be fired when keyboard shortcuts are fired with a bunch of DOM creation/manipulation crap

Step one is the most important so I'll have to double-check that it's possible.
