### ISSUE TITLE
Google Analytics Code in <head> of HTML

### ISSUE THREAD

**Issue by dustinmazon** [wvuweb/cleanslate-cms#164]
# The Question

Should we continue to load the GA script just before the `</body>` or should we place it in the `<head>` of the document?
# The Research

I would like to present the facts and rationalization as to why we should place the script in the `<head>` vs just before the `</body>`.
## Google Analytics Documentation
- https://support.google.com/analytics/answer/1008080?hl=en#GA

![screen shot 2015-06-04 at 11 47 29 am](https://cloud.githubusercontent.com/assets/1126703/7988081/8e4961ee-0aaf-11e5-83f7-6deec83a7b2f.png)
- https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced

![screen shot 2015-06-04 at 12 07 45 pm](https://cloud.githubusercontent.com/assets/1126703/7988628/5979a5ca-0ab2-11e5-8264-9c89785a086f.png)

> SUMMARY: We are using the new Universal Analytics code which is loaded asynchronously. Google recommends loading the tracking code in the `<head>` of the document.

---
## Other Articles Supporting `<head>` Insertion
- http://stackoverflow.com/questions/26755664/where-to-put-your-google-analytics-code

![screen shot 2015-06-04 at 12 42 21 pm](https://cloud.githubusercontent.com/assets/1126703/7989407/4cbee78c-0ab7-11e5-9523-aacb6351f5a1.png)
- http://www.lunametrics.com/blog/2012/02/09/where-put-google-tracking-code/

![screen shot 2015-06-04 at 12 51 12 pm](https://cloud.githubusercontent.com/assets/1126703/7989628/d4b3c26a-0ab8-11e5-8db2-51ffd7a11849.png)

![screen shot 2015-06-04 at 12 53 59 pm](https://cloud.githubusercontent.com/assets/1126703/7989630/d6c5d4da-0ab8-11e5-84fe-80c1d8aa041a.png)

> SUMMARY: We are not using custom variables and will be using event tracking so we should probably move the GA code to the `<head>` of the document to allow for more accurate metrics.
## Ease of Webmaster Tools Setup
- https://support.google.com/webmasters/answer/185871?hl=en&ref_topic=4564314

To make setting up sites with Webmaster Tools more time efficient, we should place the async GA code in the `<head>`.
## Testing Page Speed Test
- https://developers.google.com/speed/pagespeed/insights/?url=tour.wvu.edu&tab=mobile

When I run the page speed test nothing comes up about the GA code slowing down the performance. I think the async GA code isn't really a major problem.
# Conclusion

There are 4 points I would like to highlight for my suggestion of moving the GA code to the `<head>`:
1. Placing the GA code in the `<body>` or footer is an antiquated technique. The new Universal GA code loads async which doesn't prevent the page from loading the `<body>` or page content so there is no reason to load it at the bottom of the page.
2. It will be easier to set up Webmaster Tools.
3. Our GA data will be more accurate for those individuals with slower connections. 
4. Google knows what they are doing when it comes to performance, so why not listen to them and their documentation?

**Comment by adamjohnson** [comment]
This is hotly debated in the HTML5 Boilerplate:

https://github.com/h5bp/html5-boilerplate/issues/1544

And the H5BP's official stance on the topic:

https://github.com/h5bp/html5-boilerplate/blob/5.2.0/dist/doc/html.md#google-universal-analytics-tracking-code

Perhaps the best thing to do would be to make it **configurable** via a theme's `config.yml` or via Manage > Settings. But that's easy for me to say because @nreckart would be the person to implement it.

Example `config.yml`:

``` yaml
google_analytics_in_head: false
```

or 

``` yaml
google_analytics_location: 'head' # or 'body'
```

There's no question verification via Webmaster Tools (now called "Google Search Console") would be much easier if this were configurable. On all other points I follow H5BP's stances.

If making it configurable is not an option, then my vote is to keep it in the footer.

**Comment by dmolsen** [comment]
My responses:
1. While downloading the JS doesn't block the parser when using `async` running the JS after its downloaded does. Just want to clarify that `async` isn't free.
2. I would suggest that a default meta tag with a default custom data entry could do something similar. It would mean mucking with your themes though.
3. I can't argue terribly much with this but considering the lack of decisions based on stats I wouldn't sell out for that one.
4. From personal experience, each property and docs are maintained by different people. H5BP includes a dev rel rep from Google and they still suggest to have it at the bottom. There is no one true way even at Google.

Because I expect number 2 above is the driver for the issue does it seem like making the default patterns/themes include support for the meta tag solution sound ok?

**Comment by adamjohnson** [comment]
:+1: to option 2. 

``` html
<meta name="google-site-verification" content="WMsGCAOl1I_xxxxxxxx" />
```

Setting that meta tag by having a custom data attribute for the `WMsGCAOl1I_xxxxxxxx` bit from Page Properties is a great idea. Thoughts @dustinmazon?

**Comment by adamjohnson** [comment]
Here's how to implement custom data:

http://cleanslatecms.wvu.edu/how-to/theme-development/custom-data
