### ISSUE TITLE
"View" feature

### ISSUE THREAD

**Issue by osteffich** [wvuweb/cleanslate-cms#170]
When clicking the "view" link on a page -whether it is in edit mode or on the pages tab - I am directed to the homepage of the site and not the particular page that I'm trying to view. "view in new tab" works fine.

This issue happens only on sites that are live. It doesn't happen on sites in development.

**Comment by nreckart** [comment]
I'm not seeing the issue. I've checked multiple sites in production, including School of Art & Design and all links work as they should both in the Admin UI and the Editor. @osteffich, can you provide a specific example?

**Comment by osteffich** [comment]
Ok I swear it was happening on the School of Music website a few minutes ago, but now seems to be working fine. Sorry!

**Comment by nreckart** [comment]
Had you just edited the properties of a page, created a new page, moved a page, or anything like that?

**Comment by osteffich** [comment]
I had actually just created a test page because I was teaching someone how to use Cleanslate. I already deleted the page, but the issue was happening on that page specifically.

**Comment by nreckart** [comment]
**Background**
Anytime a change is made that could potentially affect any of the paths/URLs for one or more pages for a site, the system has to rebuild those paths/URLs. This process isn't as smart as it potentially could be. It basically deletes all site page paths and rebuilds them. The time this takes increases with the number of pages for a site. Prior to last week, this process was done within the web request. So if you modified a page, added a page, etc., the system would make you wait while it rebuilt everything. 

In order to speed up the web requests, last week, the process was moved out of the main web request and into a background job. The background job is processed separately from the web request, allowing the web request to respond to the user so they can go on and make further changes with less delay. So changes that affect page paths for a site are not completed immediately anymore. There will be a delay. Usually it should only be 5 - 10 seconds, but it depends on system load/usage.

**Summary**
You created the test page and tried to view the page via it's public URL before the system had a chance to actually build that URL. 

The whole thing is a work in progress and will be tweaked over time.

**Comment by nreckart** [comment]
Anybody still seeing this issue?
