### ISSUE TITLE
Feature Request: Internal Link as native menu option

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#175]
Currently, we have the ability to add internal links through the UI in editable regions only. I feel that using a feature to create a permalink menu item in your actual menu would help for a more consistent UX.

My example is as follows, but I think we should all think about how this impacts the code semantically as well, as the current solution seems to be including an additional unordered list entirely.

Page 4 has x ancestors. These ancestors appear as a sidebar navigation, rather than a drop down.  Some of the ancestors are extrenal links to other WVU websites. Some of these ancestors are internal links to pages elsewhere on this site, in order to help navigate easily to resources that apply to multiple audiences (ex: grad, or undergrad, as a grad students probably won't go to the undergrad pages while looking for information pertaining to themselves). 

Currently, we need these links to be in alpha order, but because we need to make a seperate UL, this is not possible. 

On another site, we have the same situation but they need to be in order of importants and relevance of the information that has the most clickthroughs. This, again, is not possible because some of these are internal links. 

A third site needs their side bar links re-arranged, it's a small department with a content manager who doesn't know any code, but because these internal links aren't in the CMS menu, they're not sure what to do, as they have no access to the code block in the UI do to privilage restrictions from in incident that involved abuse of the "Bold" button. Unfortunately, the college prof tech is out, and the zombie appocolyspe is happening outside. If they don't rearrange the links STAT, the whole world will be doomed because one of them has the answer for a cure!

**Comment by adamjohnson** [comment]
Lots of people are using "Add Page > External Link" for internal links because they want to build out their auto-generated navigation menus. [Diversity](http://diversity.wvu.edu), [Accessibility Services](http://accessibilityservices.wvu.edu), and [Graduate Education](http://graduate.wvu.edu) come to mind, although I'm sure most sites use this functionality at some point or another.

Maybe this could be its own modal with a Select2 or search field with the page name that the user wants to link to? I know we had performance problems with Select2 (although they [might be fixed now](https://github.com/select2/select2/issues/781#issuecomment-66678543)) & loading lots of pages into it in the past, so there might be another solution.

We could figure out a way to distinguish these types of links in Pages.

**Comment by jasonmarkle** [comment]
I know you guys are more familiar with how CS works in terms of what is going on in the code, so take this suggestion with a grain of salt because I'm not sure you could achieve the objective this way.

You basically have a way to generate the internal link already, would it be possible to add that as a menu item inside the "Create a new page" UI element that would be similar to the external link creation, but rather than it generating a new permalink it references the internal page via dropdown menu and outputs whatever that pages title is while it links to the page ID? Again, not even sure this would be valid since I don't know the way the back end of the CMS is being coded.

**Comment by TatsuJohnson** [comment]
I love the implementation of the "Internal Link" feature, but I would like to kindly suggest having the feature available when adding child pages. At the moment, you may only add them through the "Create New Page" feature.

**Comment by nreckart** [comment]
Working on it. It was an oversight.

**Comment by nreckart** [comment]
Adding an internal link page as a child should now be possible.
