### ISSUE TITLE
Forward slashes (/) in filenames break the files tab view

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#182]
Yesterday I ran in to an issue with about 10 files disappearing from view in the backend and front end of the CMS, either on the files tab, or in the link files UI element in the edit mode respectively. This isn't something that I know exactly how to recreate on another site or test environment, but feel free to use the multipleflybycapture.sandbox.wvu.edu site where it is currently happening.
1. Login to cleanslate > multiple flyby capture
2. Navigate to Files
3. You will notice there are 23 files in the site
   ![Image of Files Issue](http://i.imgur.com/Ueswfbd.png)
4. Click the next page button, you will receive the red error as seen in the top right corner as the screen shot above.

I believe this issue is because on the next page there should be a file with an odd naming convention in one of the CMS fields. It was named as if it was a reference in the back of a book with weird periods after abbreviations. I think the solution might be to just clear the .pdf files out if possible and i will re-upload, because they weren't being used at all yet.

**Comment by nreckart** [comment]
This particular issue was caused by the following file:

Didion, A.M., Lynam, A.E., “Guidance and Navigation of a Callisto-Io-Ganymede    Triple Flyby Jovian Capture”, AAS Paper 15-624, AAS/AIAA Astrodynamics Specialist    Conference, Vail, CO, August 2015.pdf

Specifically, the '/' character blew up the routing. I replaced it with a space and you can access all your files again. In the short term, refrain from using '/' in file names. For the long term, the system will be modified to disallow '/' in filenames. I'll leave this issue open until then.

**Comment by jasonmarkle** [comment]
Thank you much Nathan!

**Comment by nreckart** [comment]
Special characters, including forward slashes, should be correctly handled by the system now.
