### ISSUE TITLE
Content Version History unavailable

### ISSUE THREAD

**Issue by sfgwv** [wvuweb/cleanslate-cms#187]
When trying to view content history for orientation.wvu.edu/confirmation/schedule/parent-guest-schedule, I get this message for each of the three versions listed:

Unable to retrieve data from url: https://cleanslate.wvu.edu/sites/140/pages/6341/regions/20624/version/139279

**Comment by nreckart** [comment]
Not sure you were intending to or not, but you were viewing the history for the content region in the masthead, probably because it is the first one selected when loading the editor. The one that says "NEW STUDENT ORIENTATION". It is a global site region and there was a bug preventing the loading of history for global regions. It should be fixed now.

Regions are versioned separately, so to view the history for a specific region, you need to select it (click within it), then you can use the "History" button.

**Comment by sfgwv** [comment]
Got it. I can see the history for all of the regions now. Thanks!
