### ISSUE TITLE
Bug: Masthead in mobile gets cut off

### ISSUE THREAD

**Issue by ldbridges** [wvuweb/cleanslate-cms#188]
on my iphone 6s the masthead in brand patterns gets cut off.

**Comment by adamjohnson** [comment]
This is a valid issue, but it's not filed in the correct place. Please file this issue here:

https://github.com/wvuweb/brand-patterns/issues

and fill out the following template when you post issues:

``` markdown
## Steps to reproduce the issue

  1. Log in to CleanSlate.
  1. Click something > something.
  1. Another step.

## Results

It does this.

## Expected results

It's supposed to do this.

### Environment

  1. Operating System
  1. Browser & Browser Version

Consider attaching a screenshot from [SupportDetails.com](http://supportdetails.com) so we know where you're coming from.
```

This allows us to quickly troubleshoot and reproduce your issue; thus, enabling us to fix it faster. Thanks!
