### ISSUE TITLE
Child page path goes to / and wont change after editing properties

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#203]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Click Mining and Industrial Extension > Click Pages > Expand "Industrial Expansion Program".
3. Note the page path is /, then open page properties to see the correct page path. Save.
## Results

Nothing happens, there is not change and the page link on the sidebar will direct the users to the home page.
## Expected results

The page should save with the correct file path to begin with, but even so the page data ID should prioritize over the actual link structure itself and still give you the content of the page since said page is within the same site and / would have a different page ID
### Environment

Web Browser: Chrome 48.0.2564.103
IP Address: 157.182.40.201
Operating System: Mac OS
Screen Resolution: 2560 x 1440
Browser Size: 2560 x 1274
Javascript: Enabled
Flash Version: 20.0.-1
Colour Depth: 24 bit
Cookies: Enabled
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36

![screen-shot-2016-02-17-at-8 35 12-am](https://cloud.githubusercontent.com/assets/5209650/13111129/2c2e1d6a-d552-11e5-8b0f-a035d5471086.jpg)

**Comment by adamjohnson** [comment]
Quote from @nreckart:

> Page path building isn’t instantaneous. It’s handled in a background job. The bigger the site the longer it’ll take to build them.
> 
> 15000 page site = grab some coffee

After you create a page, it can take a few minutes (5-15 maybe) for the page path to appear in Pages. It'll get there in time.

**Comment by jasonmarkle** [comment]
Yeah that was edited less than a minute ago, but the page was created prior to launch 2 weeks ago.

**Comment by adamjohnson** [comment]
@nreckart care to weigh in?

**Comment by jasonmarkle** [comment]
@nreckart @adamjohnson This can probably be low priority. I'm sure a hot fix would be just to re-create the page, but I don't want to do that if you guys need the page there to see what's going on.

**Comment by nreckart** [comment]
The 'Organizational Development' page, directly above the page in question, is already assigned a slug value of 'sustainability'. Thus its path is '/industrial-extension/sustainability', which is what you're trying to set the page in questions path to. You can't have two pages assigned the same path. The first one is winning out. You'll need to change one of the page slugs, then things should work as expected.

The system doesn't communicate duplicate page slugs to the user, which is the real issue here. I thought there was already an open issue regarding that, but a quick search didn't turn up anything. I'll check some more and create a separate issue if I don't find one already open.

**Comment by nreckart** [comment]
Created #204 to address the main issue.
