### ISSUE TITLE
Allow for relative link paths in nav item creation

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#216]
When creating links on the nav menu, you cannot use a relative path. In turn, this means that you cannot create links that will go to specific sections. 

This could be alleviated if we were to adjust the Web Address field so that it accepts relative paths or an alternate format under the internal links modal in the page builder. Open to additional ideas and comments.

**Comment by nreckart** [comment]
@adamjohnson Is this still relevant?

**Comment by adamjohnson** [comment]
Indeed, it looks like CleanSlate prepends `https://` onto URLs that have been created via Pages > Create Page > External Link. For example, if you put `how-to/theme-development/blog-templates#blog-post-migration` in the "Web Address" field in the External Link modal, CleanSlate outputs `https://how-to/theme-development/blog-templates#blog-post-migration` as the href value for the link.

I don't think this is a big deal since we can easily target an external link like this via a custom `id` or `class`. We can then modify the URL like so:

```js
(function () {
  'use strict';
  const getLink = document.querySelector('#js-modify-url');
  getLink.setAttribute('href', '/relative-path/to/your/page#id-in-page');
})();
```

I would wager prepending the `https://` in this field has safeguarded more people than if we did the opposite.
