### ISSUE TITLE
Alternative name option for articles

### ISSUE THREAD

**Issue by sarahgibbons** [wvuweb/cleanslate-cms#217]
The tag for using the alternative name, but for articles:
`<r:page:alternate_name />`

![screen shot 2016-08-19 at 11 50 35 am](https://cloud.githubusercontent.com/assets/19209420/17815677/5d4d3c72-6603-11e6-923d-c896ed412b8a.png)

I realize this is a low priority, but it would be helpful for front page sections pulling in news articles with really long titles.

**Comment by nreckart** [comment]
You can technically do this already. An article is basically the same as a page, but there are some additional tags available for articles. So, you can actually use `<r:page:alternate_name />` for an article; however, you probably wouldn't want to do that in practice, because it would require every article to have an 'alternate_name'. If one doesn't have an 'alternate_name', nothing would be output.

What you would probably want to do is:

 `<r:page:first_non_blank_attr names="alternate_name, name" />`

This will output the first non blank attribute value from the attributes given in 'names' (a comma separated list).

**Comment by sarahgibbons** [comment]
That worked! Thanks so much for your help!
