### ISSUE TITLE
Unpublish/Publish seems to be "stuck" for certain pages

### ISSUE THREAD

**Issue by cherisealeen** [wvuweb/cleanslate-cms#255]
We recently unpublished a bunch of child pages under the IT Services - Old parent category. I was going through all the child pages yesterday to make sure they are excluded from navigation and search engines and noticed that some were mysteriously listed as "published" even though they had been unpublished a while ago. When I would click "Unpublish" to unpublish them again, the success notifications said the pages had been published...

This is only affecting around seven pages that I know of. I confirmed with a co-worker that I'm not the only one seeing this problem. The pages appear to be "stuck" because they are still saying published "less than a minute ago" even though we went through all of this yesterday. I tried my best to capture the confusion in screenshots.

Thanks for your help!

![Screen Shot 2019-10-09 at 10 53 11 AM](https://user-images.githubusercontent.com/56356518/66492989-5178d700-ea83-11e9-89e5-da9853f3718c.png)
![Screen Shot 2019-10-09 at 10 43 41 AM](https://user-images.githubusercontent.com/56356518/66492994-52aa0400-ea83-11e9-8909-ab8d6476ecab.png)

**Comment by nreckart** [comment]
@cherisealeen All of the pages in question here appear to be external link pages, not content pages. They simply redirect to whatever URL they are linked to and are essentially always published. 

The issue here is with the UI. The publish/unpublish action should not be displayed for external link pages, nor should the "less than a minute ago". We will look into fixing this, but for now, if you really don't want to pages to redirect, I would suggest just deleting them.

**Comment by cherisealeen** [comment]
That makes total sense.

Thanks for your help!
