### ISSUE TITLE
Allow users to use WebP and AVIF images in Files

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#276]
## Steps to reproduce the issue

  1. To [Files](https://cleanslate.wvu.edu/sites/5/uploads) of aj.sandbox.wvu.edu
  1. Note the last two images uploaded are an `.avif` and `.webp` image.
     * Their names are: `brownfields-home-hero-dscn-3696-1780x1780` if they get buried.
  1. Go to any page in Pages and hit Edit in new tab
  1. Click an editable region and try to insert either the `.webp` image or the `.avif` image via the insert media modal.

## Results

You'll notice in the CleanSlate Files / Insert Media modal that `.webp` and `.avif` images are not considered "Images" when the "Type > Image" filter is automatically checked on the left. This means you cannot upload either of these formats to CleanSlate and use them on a page.

Also, if you try to access the image via its [public URL](https://aj.sandbox.wvu.edu/files/7706cf8c-23a4-4e43-ba3d-48d49a87ca87/brownfields-home-hero-dscn-3696-1780x1780.webp), you get a 404 error.

## Expected results

CleanSlate should let users upload and use `.webp` and `.avif` images.

## Background / Resources

  * [Using modern image formats](https://www.smashingmagazine.com/2021/09/modern-image-formats-avif-webp/) by SmashingMag

**Comment by nreckart** [comment]
Enabling WebP was as simple as registering the .webp extension as a valid image format within CleanSlate. 

Not so simple with AVIF. Turns out that the version of the library used to process the images (ImageMagick) doesn't seem to fully support AVIF. I attempted to custom compile the newest version of ImageMagick in my dev environment, but it turns out that's not so trivial and I was still not able to get AVIF to work. I'll have to revisit it at a later date. Hopefully the official ImageMagick packages will get updated soon.

WebP images should work in production now.

**Comment by adamjohnson** [comment]
I can confirm WebP does work in Files in production right now. Thanks! I will close this issue and we can revisit AVIF later when it's supported across more browsers (Edge and Safari lacking as of this date).

Fun fact, I just replaced a transparent PNG at 735KB with a WebP image at 129KB. Big difference!
